### ISSUE TITLE
Support for Laravel 10?

### ISSUE THREAD

**Issue by nekhbet** [Hydrat-Agency/laravel-db-dumper#1]
Problem 1
    - Root composer.json requires hydrat-agency/laravel-db-dumper * -> satisfiable by hydrat-agency/laravel-db-dumper[v1.0.0].
    - hydrat-agency/laravel-db-dumper v1.0.0 **requires illuminate/contracts ^9.0 -> found illuminate/contracts[v9.0.0, ..., v9.52.16]** but these were not loaded, likely because it conflicts with another require.

Thanks!

**Comment by tgeorgel** [comment]
Hey @nekhbet,

Please upgrade to `v1.1.0` for Laravel 10 support.

**Comment by nekhbet** [comment]
Ahh, got it. Thank you :D
