### ISSUE TITLE
Import command .. handling of big files

### ISSUE THREAD

**Issue by nekhbet** [Hydrat-Agency/laravel-db-dumper#2]
Any plans to redo the import of bigger files? Like reading in batches and executing them like that. Think of 1-2GB.

Thanks!

**Comment by tgeorgel** [comment]
Unfortunately, I think the better way to manage large SQL file would be to split the SQL in multiple smaller chunk part from the start.

I'll think about a solution for this kind of file.

**Comment by nekhbet** [comment]
Or, hmm .. seeing that the export works by, at least for mysql/mariadb, via mysqldump .. why not use the same with the import? (of course, by using the "mysql -uUSER -pPASS -D DB_NAME < OUR_DUMP_FILE) ?
